### ISSUE TITLE
Make it clearer that this library does not (yet) support going from string to Undate object, i.e. it doesn't have a parser

### ISSUE THREAD

**Issue by corneliusroemer** [dh-tech/undate-python#102]
I'm currently looking for a parser that handles incomplete dates as using pandas non-public API method `parsing.parse_datetime_string_with_reso` is not very future proof. It does the job but we're getting bitten by various deprecations over time.

Would be super nice if undate supported parsing, I haven't yet found a good parser, let me know if you know of one.

In general, it'd be cool if you could show a 101 usage prominently in the README to show what the library actually does - it took going to the tests to figure it out for me.

**Comment by rlskoeser** [comment]
@corneliusroemer thanks for the feedback.  I have a bunch of updates in the develop branch that I'm hoping to release soon, which includes a bit more of an overview in the readme and a bunch of other functionality. I've been working on EDTF parsing support among other things.

What kind of dates are you trying to parse?  If I can get a new release out soon would it be something you might be able to use?

**Comment by rlskoeser** [comment]
Released v0.3, which adds a clearer statement about the limitations of the current version and adds more example usage.

I'm always interested in more use cases and examples, so it would be great if you want to open an issue with more details on what you were hoping this library would do for you and some example data.
