### ISSUE TITLE
Publish to PyPi

### ISSUE THREAD

**Issue by ColeDCrawford** [dh-tech/undate-python#21]
- [x] #12 
- [x] determine group/maintainers for pypi and credentials
- [x] configure appropriate github secret for publishing on pypi
- [x] add pypi publish github action workflow
- [x] create a first release on github

**Comment by maltevogl** [comment]
We could also consider to setup an automated publishing to Zenodo on each release? https://zenodo.org/

**Comment by rlskoeser** [comment]
invited maintainers on DHTech slack; we have at least two now, will add others as they request; considering this task complete
