### ISSUE TITLE
Allow partially known dates

### ISSUE THREAD

**Issue by jdamerow** [dh-tech/undate-python#3]
In Undate class, right now it allows dates without a year, but it would be good if it would allow, for example, missing digits (e.g. 1991-1?-10).

- [x] support missing digits when initializing undate instance; calculate earliest/latest possible dates based on known digits
- [x] handle missing digits in string method
- [x] update duration methods for partially known dates
- [x] track date granularity/precision

**Comment by rlskoeser** [comment]
initial implementation completed in #36
