### ISSUE TITLE
Set up docs

### ISSUE THREAD

**Issue by ColeDCrawford** [dh-tech/undate-python#37]
Sphinx?

**Comment by rlskoeser** [comment]
Could also use mkdocs — seems like it might be a bit easier to get up and running? I'm more familiar with sphinx, but have used mkdocs a bit. I have examples of github actions workflows for building and publishing either of these.

Should be possible to set up a docs coverage check on PRs, too. I figured out a way to do that for sphinx, but looks like there's a coverage plugin for mkdocs as well.

**Comment by rlskoeser** [comment]
@all-contributors
please add @maltevogl for documentation

**Comment by rlskoeser** [comment]
should we consider this task complete, and add a separate issue to setup readthedocs when we're ready?

**Comment by maltevogl** [comment]
We have now a readthedocs: https://undate-python.readthedocs.io 
and could add the button like this 
[![Documentation Status](https://readthedocs.org/projects/undate-python/badge/?version=latest)](https://undate-python.readthedocs.io/en/latest/?badge=latest)

**Comment by rlskoeser** [comment]
added badge & link to readme, considering this complete
