### ISSUE TITLE
implement labels for undate and undate interval

### ISSUE THREAD

**Issue by rlskoeser** [dh-tech/undate-python#6]
there's a placeholder label attribute for undate, but we aren't doing anything with it yet

proposed initial implementation:
- add label field to `UndateInterval`
- for both `Undate` and `UndateInterval`, add optional label parameter to init method that sets the label
- for both, if label is set then it should be included in the string representation and `repr`; maybe something like `label (dates)` if label is defined

**Comment by jdamerow** [comment]
completed in https://github.com/dh-tech/undate-python/pull/52
